/* Generated By:JavaCC: Do not edit this line. YakaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface YakaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MOINS = 9;
  /** RegularExpression Id. */
  int MUL = 10;
  /** RegularExpression Id. */
  int DIV = 11;
  /** RegularExpression Id. */
  int INF = 12;
  /** RegularExpression Id. */
  int SUP = 13;
  /** RegularExpression Id. */
  int INFEGAL = 14;
  /** RegularExpression Id. */
  int SUPEGAL = 15;
  /** RegularExpression Id. */
  int EGAL = 16;
  /** RegularExpression Id. */
  int DIFF = 17;
  /** RegularExpression Id. */
  int ET = 18;
  /** RegularExpression Id. */
  int OU = 19;
  /** RegularExpression Id. */
  int NON = 20;
  /** RegularExpression Id. */
  int BOOLEEN = 21;
  /** RegularExpression Id. */
  int VAR = 22;
  /** RegularExpression Id. */
  int FAIRE = 23;
  /** RegularExpression Id. */
  int SINON = 24;
  /** RegularExpression Id. */
  int POUR = 25;
  /** RegularExpression Id. */
  int SI = 26;
  /** RegularExpression Id. */
  int FSI = 27;
  /** RegularExpression Id. */
  int ENTIER = 28;
  /** RegularExpression Id. */
  int RETOURNE = 29;
  /** RegularExpression Id. */
  int VRAI = 30;
  /** RegularExpression Id. */
  int TANTQUE = 31;
  /** RegularExpression Id. */
  int CONST = 32;
  /** RegularExpression Id. */
  int FAUX = 33;
  /** RegularExpression Id. */
  int FAIT = 34;
  /** RegularExpression Id. */
  int FONCTION = 35;
  /** RegularExpression Id. */
  int FFONCTION = 36;
  /** RegularExpression Id. */
  int PROGRAMME = 37;
  /** RegularExpression Id. */
  int FPROGRAMME = 38;
  /** RegularExpression Id. */
  int PRINCIPAL = 39;
  /** RegularExpression Id. */
  int FPRINCIPAL = 40;
  /** RegularExpression Id. */
  int ALORS = 41;
  /** RegularExpression Id. */
  int ECRIRE = 42;
  /** RegularExpression Id. */
  int LIRE = 43;
  /** RegularExpression Id. */
  int ALALIGNE = 44;
  /** RegularExpression Id. */
  int chiffre = 45;
  /** RegularExpression Id. */
  int entier = 46;
  /** RegularExpression Id. */
  int lettre = 47;
  /** RegularExpression Id. */
  int ident = 48;
  /** RegularExpression Id. */
  int chaine = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(*\"",
    "<token of kind 6>",
    "\"*)\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"<>\"",
    "\"ET\"",
    "\"OU\"",
    "\"NON\"",
    "\"BOOLEEN\"",
    "\"VAR\"",
    "\"FAIRE\"",
    "\"SINON\"",
    "\"POUR\"",
    "\"SI\"",
    "\"FSI\"",
    "\"ENTIER\"",
    "\"RETOURNE\"",
    "\"VRAI\"",
    "\"TANTQUE\"",
    "\"CONST\"",
    "\"FAUX\"",
    "\"FAIT\"",
    "\"FONCTION\"",
    "\"FFONCTION\"",
    "\"PROGRAMME\"",
    "\"FPROGRAMME\"",
    "\"PRINCIPAL\"",
    "\"FPRINCIPAL\"",
    "\"ALORS\"",
    "\"ECRIRE\"",
    "\"LIRE\"",
    "\"ALALIGNE\"",
    "<chiffre>",
    "<entier>",
    "<lettre>",
    "<ident>",
    "<chaine>",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
